import { Dataset, GovernanceTask, User, Department, Domain } from './types';

export const MOCK_USER: User = {
  name: 'Alisher Yerzhanov',
  email: 'a.yerzhanov@astana.gov.kz',
  department: 'Architecture and Urban Planning Department',
  role: 'Head of Department',
  userRole: 'steward',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alisher',
};

export const DEPARTMENTS: Department[] = [
  { id: 'D1', name: { ru: 'Управление архитектуры и градостроительства', en: 'Architecture and Urban Planning Department' } },
  { id: 'D2', name: { ru: 'Управление земельных отношений', en: 'Land Relations Department' } },
  { id: 'D3', name: { ru: 'Управление строительства', en: 'Construction Department' } },
  { id: 'D4', name: { ru: 'Управление транспорта и развития дорожно-транспортной инфраструктуры', en: 'Transport and Road Infrastructure Department' } },
  { id: 'D5', name: { ru: 'Управление пассажирского транспорта', en: 'Public Transport Department' } },
  { id: 'D6', name: { ru: 'Управление образования', en: 'Education Department' } },
  { id: 'D7', name: { ru: 'Управление здравоохранения', en: 'Healthcare Department' } },
  { id: 'D8', name: { ru: 'Управление занятости и социальных программ', en: 'Employment and Social Programs Department' } },
  { id: 'D9', name: { ru: 'Управление энергетики и коммунального хозяйства', en: 'Energy and Utilities Department' } },
  { id: 'D10', name: { ru: 'Управление жилья и жилищной инспекции', en: 'Housing and Housing Inspection Department' } },
  { id: 'D11', name: { ru: 'Управление финансов', en: 'Finance Department' } },
  { id: 'D12', name: { ru: 'Управление предпринимательства', en: 'Entrepreneurship Department' } },
  { id: 'D13', name: { ru: 'Управление экологии и охраны окружающей среды', en: 'Ecology and Environmental Protection Department' } },
  { id: 'D14', name: { ru: 'Управление цифровизации', en: 'Digital Transformation Department' } },
  { id: 'D15', name: { ru: 'Управление культуры', en: 'Culture Department' } },
];

export const DOMAINS: Domain[] = [
  {
    id: 'DOM1',
    name: { ru: 'Территория и землепользование', en: 'Territory & Land Use' },
    icon: 'Building2',
    categories: [
      { id: 'CAT1.1', name: { ru: 'Кадастр и земельные участки', en: 'Cadastre & Land Parcels' } },
      { id: 'CAT1.2', name: { ru: 'Градостроительное планирование', en: 'Urban Planning' } },
      { id: 'CAT1.3', name: { ru: 'Здания и сооружения', en: 'Buildings & Structures' } },
    ],
  },
  {
    id: 'DOM2',
    name: { ru: 'Население и социальная сфера', en: 'Population & Social Services' },
    icon: 'Users',
    categories: [
      { id: 'CAT2.1', name: { ru: 'Демография', en: 'Demographics' } },
      { id: 'CAT2.2', name: { ru: 'Образование', en: 'Education' } },
      { id: 'CAT2.3', name: { ru: 'Здравоохранение', en: 'Healthcare' } },
      { id: 'CAT2.4', name: { ru: 'Социальная защита', en: 'Social Services' } },
    ],
  },
  {
    id: 'DOM3',
    name: { ru: 'Транспорт и мобильность', en: 'Transport & Mobility' },
    icon: 'Car',
    categories: [
      { id: 'CAT3.1', name: { ru: 'Дорожная сеть', en: 'Road Network' } },
      { id: 'CAT3.2', name: { ru: 'Общественный транспорт', en: 'Public Transport' } },
      { id: 'CAT3.3', name: { ru: 'Парковки и велоинфраструктура', en: 'Parking & Cycling' } },
    ],
  },
  {
    id: 'DOM4',
    name: { ru: 'Экология и окружающая среда', en: 'Ecology & Environment' },
    icon: 'Leaf',
    categories: [
      { id: 'CAT4.1', name: { ru: 'Качество воздуха', en: 'Air Quality' } },
      { id: 'CAT4.2', name: { ru: 'Зелёная инфраструктура', en: 'Green Infrastructure' } },
      { id: 'CAT4.3', name: { ru: 'Водные ресурсы', en: 'Water Resources' } },
    ],
  },
  {
    id: 'DOM5',
    name: { ru: 'Инженерная инфраструктура', en: 'Engineering Infrastructure' },
    icon: 'Wrench',
    categories: [
      { id: 'CAT5.1', name: { ru: 'Коммунальные сети', en: 'Utility Networks' } },
      { id: 'CAT5.2', name: { ru: 'Благоустройство', en: 'Public Amenities' } },
    ],
  },
  {
    id: 'DOM6',
    name: { ru: 'Экономика и бюджет', en: 'Economy & Budget' },
    icon: 'Coins',
    categories: [
      { id: 'CAT6.1', name: { ru: 'Бюджет города', en: 'City Budget' } },
      { id: 'CAT6.2', name: { ru: 'Предпринимательство', en: 'Entrepreneurship' } },
    ],
  },
  {
    id: 'DOM7',
    name: { ru: 'Безопасность и ЧС', en: 'Safety & Emergency' },
    icon: 'Shield',
    categories: [
      { id: 'CAT7.1', name: { ru: 'Чрезвычайные ситуации', en: 'Emergencies' } },
      { id: 'CAT7.2', name: { ru: 'Общественная безопасность', en: 'Public Safety' } },
    ],
  },
];

export const DATASETS: Dataset[] = [
  // DOMAIN 1
  {
    id: '1',
    name: { ru: 'Реестр земельных участков г. Астаны (полигоны, целевое назначение)', en: 'Astana Land Parcels Registry (polygons, purpose)' },
    description: { ru: 'Реестр земельных участков г. Астаны с указанием целевого назначения и границ.', en: 'Registry of land parcels in Astana with purpose and boundaries.' },
    departmentId: 'D2', domainId: 'DOM1', categoryId: 'CAT1.1', type: 'Geodata', format: 'SHP', qualityScore: 91, lastUpdated: '2025-01-15', frequency: 'Quarterly', access: 'By Request', status: 'active', isPrivate: false, tags: ['land', 'cadastre'], popularity: 85,
    ownerName: 'Азамат С.', userRating: 4.5, userReviewsCount: 12, completenessScore: 94,
    expertAssessment: {
      expertName: 'Ерлан М.',
      accuracy: 92,
      relevance: 95,
      stewardReview: 'approved',
      lastAssessed: '2024-11-20',
      date: '2024-11-20',
      comment: {
        ru: 'Данные актуальны, но требуют уточнения по границам в районе Нұра.',
        en: 'Data is up to date, but requires clarification on boundaries in the Nura district.'
      }
    }
  },
  {
    id: '2',
    name: { ru: 'Кадастровая карта земельных участков', en: 'Cadastral Map of Land Parcels' },
    description: { ru: 'Публичная кадастровая карта земельных участков города.', en: 'Public cadastral map of city land parcels.' },
    departmentId: 'D2', domainId: 'DOM1', categoryId: 'CAT1.1', type: 'Geodata', format: 'GeoJSON', qualityScore: 88, lastUpdated: '2024-12-01', frequency: 'Quarterly', access: 'Open', status: 'active', isPrivate: false, tags: ['map', 'cadastre'], popularity: 92,
    ownerName: 'Азамат С.', userRating: 4.2, userReviewsCount: 28, completenessScore: 90
  },
  {
    id: '3',
    name: { ru: 'Функциональное зонирование территории', en: 'Functional Zoning of Territory' },
    description: { ru: 'Карта функционального зонирования территории города.', en: 'Map of functional zoning of the city territory.' },
    departmentId: 'D1', domainId: 'DOM1', categoryId: 'CAT1.1', type: 'Geodata', format: 'SHP', qualityScore: 94, lastUpdated: '2024-06-20', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['zoning', 'planning'], popularity: 78
  },
  {
    id: '4',
    name: { ru: 'Генеральный план г. Астаны 2035', en: 'Astana Master Plan 2035' },
    description: { ru: 'Основной градостроительный документ развития города до 2035 года.', en: 'Main urban planning document for city development until 2035.' },
    departmentId: 'D1', domainId: 'DOM1', categoryId: 'CAT1.2', type: 'Document', format: 'PDF', qualityScore: 97, lastUpdated: '2024-03-10', frequency: 'Once', access: 'Open', status: 'active', isPrivate: false, tags: ['masterplan', 'planning'], popularity: 95,
    ownerName: 'Бахытжан К.', userRating: 4.8, userReviewsCount: 156, completenessScore: 100,
    expertAssessment: {
      expertName: 'Комитет по делам строительства',
      accuracy: 100,
      relevance: 100,
      stewardReview: 'approved',
      lastAssessed: '2024-03-10',
      date: '2024-03-10',
      comment: {
        ru: 'Официальный утвержденный документ.',
        en: 'Official approved document.'
      }
    }
  },
  {
    id: '5',
    name: { ru: 'Правила землепользования и застройки (ПЗЗ)', en: 'Land Use and Development Rules' },
    description: { ru: 'Нормативно-правовой акт, устанавливающий правила застройки.', en: 'Regulatory act establishing development rules.' },
    departmentId: 'D1', domainId: 'DOM1', categoryId: 'CAT1.2', type: 'Document', format: 'PDF', qualityScore: 95, lastUpdated: '2024-08-15', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['rules', 'zoning'], popularity: 70
  },
  {
    id: '6',
    name: { ru: 'Проекты детальной планировки (ПДП) по районам', en: 'Detailed Planning Projects (DPP) by Districts' },
    description: { ru: 'Детальные планы застройки отдельных районов города.', en: 'Detailed development plans for specific city districts.' },
    departmentId: 'D1', domainId: 'DOM1', categoryId: 'CAT1.2', type: 'Geodata', format: 'SHP', qualityScore: 82, lastUpdated: '2025-02-01', frequency: 'As needed', access: 'By Request', status: 'active', isPrivate: false, tags: ['dpp', 'planning'], popularity: 65
  },
  {
    id: '7',
    name: { ru: 'Реестр многоквартирных жилых домов', en: 'Registry of Multi-apartment Residential Buildings' },
    description: { ru: 'Список всех многоквартирных жилых домов города.', en: 'List of all multi-apartment residential buildings in the city.' },
    departmentId: 'D10', domainId: 'DOM1', categoryId: 'CAT1.3', type: 'Table', format: 'Excel', qualityScore: 79, lastUpdated: '2025-01-20', frequency: 'Quarterly', access: 'Open', status: 'active', isPrivate: false, tags: ['housing', 'buildings'], popularity: 88,
    ownerName: 'Марат К.', userRating: 3.8, userReviewsCount: 5, completenessScore: 82,
    expertAssessment: {
      expertName: 'Марат К.',
      accuracy: 85,
      relevance: 90,
      stewardReview: 'pending',
      lastAssessed: '2025-01-20',
      date: '2025-01-20',
      comment: {
        ru: 'Реестр обновлен, добавлены новые ЖК в районе Сарыарка.',
        en: 'Registry updated, new residential complexes in Saryarka district added.'
      }
    }
  },
  {
    id: '8',
    name: { ru: 'Реестр разрешений на строительство 2020-2025', en: 'Construction Permits Registry 2020-2025' },
    description: { ru: 'Данные о выданных разрешениях на строительство.', en: 'Data on issued construction permits.' },
    departmentId: 'D3', domainId: 'DOM1', categoryId: 'CAT1.3', type: 'Table', format: 'CSV', qualityScore: 86, lastUpdated: '2025-02-28', frequency: 'Monthly', access: 'Open', status: 'active', isPrivate: false, tags: ['permits', 'construction'], popularity: 82,
    ownerName: 'Айгерим С.', userRating: 4.1, userReviewsCount: 34, completenessScore: 88
  },
  {
    id: '9',
    name: { ru: 'Реестр аварийного и ветхого жилья', en: 'Emergency and Dilapidated Housing Registry' },
    description: { ru: 'Список домов, признанных аварийными или ветхими.', en: 'List of houses recognized as emergency or dilapidated.' },
    departmentId: 'D10', domainId: 'DOM1', categoryId: 'CAT1.3', type: 'Table', format: 'Excel', qualityScore: 72, lastUpdated: '2024-09-30', frequency: 'Annually', access: 'Restricted', status: 'active', isPrivate: false, tags: ['emergency', 'housing'], popularity: 55
  },

  {
    id: '10.1',
    name: { ru: 'Плотность населения по районам, 2023', en: 'Population Density by Districts, 2023' },
    description: { 
      ru: 'Набор данных содержит информацию о плотности населения по административным районам и микрорайонам города Астаны за 2023 год. Данные основаны на материалах Бюро национальной статистики и скорректированы с учётом административных данных о регистрации по месту жительства. Пространственная привязка выполнена по границам районов и кварталов. Датасет используется для градостроительного планирования, оценки обеспеченности социальной инфраструктурой и расчёта нагрузки на транспортную сеть.', 
      en: 'This dataset contains information on population density by administrative districts and micro-districts of Astana for 2023. The data is based on materials from the Bureau of National Statistics and adjusted for administrative data on residence registration. Spatial reference is performed along the boundaries of districts and blocks. The dataset is used for urban planning, assessing the provision of social infrastructure, and calculating the load on the transport network.' 
    },
    departmentId: 'D1', domainId: 'DOM2', categoryId: 'CAT2.1', type: 'Geodata', format: 'SHP', qualityScore: 98, lastUpdated: '2024-02-15', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['население', 'плотность', 'демография', '2023', 'районы'], popularity: 98,
    ownerName: 'Алибек Т.', userRating: 4.9, userReviewsCount: 42, completenessScore: 99,
    expertAssessment: {
      expertName: 'Д-р Сауле А.',
      accuracy: 98,
      relevance: 100,
      stewardReview: 'approved',
      lastAssessed: '2024-03-05',
      date: '2024-03-05',
      comment: {
        ru: 'Высочайшая точность данных. Методология сбора соответствует международным стандартам ООН-Хабитат.',
        en: 'Highest data accuracy. The collection methodology complies with international UN-Habitat standards.'
      }
    },
    userReviews: [
      { id: 'rev1', userName: 'Марат Б.', department: { ru: 'Управление транспорта', en: 'Transport Department' }, date: '2024-03-01', rating: 5, comment: 'Отличный датасет для анализа инфраструктуры.' }
    ],
    steward: { 
      ru: 'Сержан К.', en: 'Sanzhar K.', 
      role: { ru: 'Ведущий специалист отдела ГИС', en: 'Lead GIS Specialist' },
      email: 's.kurmanov@astana.gov.kz', phone: '+7 (7172) 55-01-01' 
    },
    volume: '124 MB',
    crs: 'EPSG:4326 (WGS 84)',
    source: { ru: 'Бюро национальной статистики РК', en: 'Bureau of National Statistics of the Republic of Kazakhstan' },
    publishedDate: '2024-03-10',
    license: { ru: 'Для внутреннего использования', en: 'For internal use' },
    schema: [
      { id: 1, name: 'id', type: 'integer', description: { ru: 'Уникальный идентификатор', en: 'Unique identifier' }, example: '1042', required: true, completeness: 100, source: 'system' },
      { id: 2, name: 'district_name', type: 'varchar(100)', description: { ru: 'Название района', en: 'District name' }, example: '"Есиль"', required: true, completeness: 100, source: 'system' },
      { id: 3, name: 'district_code', type: 'varchar(10)', description: { ru: 'Код КАТО района', en: 'District KATO code' }, example: '"7110"', required: true, completeness: 100, source: 'system' },
      { id: 4, name: 'population_total', type: 'integer', description: { ru: 'Численность населения', en: 'Total population' }, example: '187450', required: true, completeness: 100, source: 'system' },
      { id: 5, name: 'population_male', type: 'integer', description: { ru: 'Мужское население', en: 'Male population' }, example: '89200', required: false, completeness: 94, source: 'manual' },
      { id: 6, name: 'population_female', type: 'integer', description: { ru: 'Женское население', en: 'Female population' }, example: '98250', required: false, completeness: 94, source: 'manual' },
      { id: 7, name: 'area_sq_km', type: 'float', description: { ru: 'Площадь (кв. км)', en: 'Area (sq. km)' }, example: '32.4', required: true, completeness: 100, source: 'system' },
      { id: 8, name: 'density_per_sq_km', type: 'float', description: { ru: 'Плотность (чел/кв.км)', en: 'Density (people/sq.km)' }, example: '5785.5', required: true, completeness: 100, source: 'system' },
      { id: 9, name: 'year', type: 'integer', description: { ru: 'Отчётный год', en: 'Reporting year' }, example: '2023', required: true, completeness: 100, source: 'system' },
      { id: 10, name: 'geometry', type: 'MultiPolygon', description: { ru: 'Границы района', en: 'District boundaries' }, example: 'POLYGON((...))', required: true, completeness: 100, source: 'system' },
    ],
    lineage: {
      sources: [
        { id: 'src1', name: { ru: 'Бюро национальной статистики РК', en: 'Bureau of National Statistics RK' }, type: 'external', owner: { ru: 'Республиканский орган', en: 'Republican body' }, method: { ru: 'Официальный запрос', en: 'Official request' }, frequency: { ru: 'Ежегодно', en: 'Annually' } },
        { id: 'src2', name: { ru: 'Адресный регистр (ГБД)', en: 'Address Register (GBD)' }, type: 'system', owner: { ru: 'Управление цифровизации', en: 'Digital Transformation Department' }, method: { ru: 'API-интеграция', en: 'API integration' }, frequency: { ru: 'Ежеквартально', en: 'Quarterly' } },
      ],
      consumers: [
        { id: 'cons1', name: { ru: 'Генеральный план г. Астаны 2035', en: 'Astana Master Plan 2035' }, type: 'analysis', owner: { ru: 'Упр. архитектуры', en: 'Architecture Dept' } },
        { id: 'cons2', name: { ru: 'Зоны обслуживания поликлиник', en: 'Clinic Service Zones' }, type: 'analysis', owner: { ru: 'Упр. здравоохранения', en: 'Healthcare Dept' } },
        { id: 'cons3', name: { ru: 'Квартальный отчёт по соц. инфраструктуре', en: 'Quarterly Social Infrastructure Report' }, type: 'report', owner: { ru: 'Упр. строительства', en: 'Construction Dept' } },
      ]
    },
    previewRows: [
      { district_name: 'Есиль', population_total: 187450, area_sq_km: 32.4, density_per_sq_km: 5785, year: 2023 },
      { district_name: 'Алматы', population_total: 264300, area_sq_km: 28.1, density_per_sq_km: 9405, year: 2023 },
      { district_name: 'Сарыарка', population_total: 342100, area_sq_km: 68.7, density_per_sq_km: 4979, year: 2023 },
      { district_name: 'Байконыр', population_total: 198600, area_sq_km: 15.8, density_per_sq_km: 12570, year: 2023 },
      { district_name: 'Нұра', population_total: 156200, area_sq_km: 45.2, density_per_sq_km: 3456, year: 2023 },
    ],
    statistics: {
      totalRecords: 8,
      min: 3456,
      max: 12570,
      avg: 6842,
      sum: 1348650,
      unit: { ru: 'чел/кв.км', en: 'people/sq.km' }
    }
  },
  // DOMAIN 2
  {
    id: '10',
    name: { ru: 'Численность населения по районам (ежегодная)', en: 'Population Count by Districts (Annual)' },
    description: { ru: 'Статистика численности населения в разрезе районов.', en: 'Population statistics by district.' },
    departmentId: 'D11', domainId: 'DOM2', categoryId: 'CAT2.1', type: 'Table', format: 'Excel', qualityScore: 96, lastUpdated: '2025-01-10', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['population', 'stats'], popularity: 91,
    ownerName: 'Алибек Т.', userRating: 4.7, userReviewsCount: 89, completenessScore: 98
  },
  {
    id: '11',
    name: { ru: 'Половозрастная структура населения', en: 'Age and Gender Structure of Population' },
    description: { ru: 'Распределение населения по полу и возрасту.', en: 'Distribution of population by gender and age.' },
    departmentId: 'D11', domainId: 'DOM2', categoryId: 'CAT2.1', type: 'Table', format: 'CSV', qualityScore: 94, lastUpdated: '2025-01-10', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['demographics', 'age'], popularity: 84
  },
  {
    id: '12',
    name: { ru: 'Данные внутренней миграции (прибытие/выбытие)', en: 'Internal Migration Data (Arrival/Departure)' },
    description: { ru: 'Статистика перемещения населения внутри страны.', en: 'Statistics of population movement within the country.' },
    departmentId: 'D11', domainId: 'DOM2', categoryId: 'CAT2.1', type: 'Table', format: 'Excel', qualityScore: 78, lastUpdated: '2024-12-15', frequency: 'Annually', access: 'By Request', status: 'active', isPrivate: false, tags: ['migration', 'demographics'], popularity: 62
  },
  {
    id: '13',
    name: { ru: 'Реестр школ г. Астаны (координаты, вместимость)', en: 'Astana Schools Registry (coordinates, capacity)' },
    description: { ru: 'Список всех школ города с геоданными и мощностью.', en: 'List of all city schools with geodata and capacity.' },
    departmentId: 'D6', domainId: 'DOM2', categoryId: 'CAT2.2', type: 'Geodata', format: 'GeoJSON', qualityScore: 91, lastUpdated: '2025-02-01', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['schools', 'education'], popularity: 89,
    ownerName: 'Елена В.', userRating: 4.6, userReviewsCount: 22, completenessScore: 95,
    expertAssessment: {
      expertName: 'Елена В.',
      accuracy: 94,
      relevance: 98,
      stewardReview: 'pending',
      lastAssessed: '2025-02-01',
      date: '2025-02-01',
      comment: {
        ru: 'Координаты проверены по данным 2024 года.',
        en: 'Coordinates verified according to 2024 data.'
      }
    }
  },
  {
    id: '14',
    name: { ru: 'Реестр детских садов (координаты, заполненность)', en: 'Kindergartens Registry (coordinates, occupancy)' },
    description: { ru: 'Данные о детских садах города.', en: 'Data on city kindergartens.' },
    departmentId: 'D6', domainId: 'DOM2', categoryId: 'CAT2.2', type: 'Geodata', format: 'GeoJSON', qualityScore: 87, lastUpdated: '2025-01-15', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['kindergarten', 'education'], popularity: 85
  },
  {
    id: '15',
    name: { ru: 'Данные очереди в дошкольные учреждения', en: 'Preschool Waiting List Data' },
    description: { ru: 'Статистика очередности в детские сады.', en: 'Statistics of kindergarten waiting lists.' },
    departmentId: 'D6', domainId: 'DOM2', categoryId: 'CAT2.2', type: 'Table', format: 'Excel', qualityScore: 83, lastUpdated: '2025-03-01', frequency: 'Monthly', access: 'By Request', status: 'active', isPrivate: false, tags: ['waitinglist', 'education'], popularity: 76
  },
  {
    id: '16',
    name: { ru: 'Реестр медицинских учреждений (поликлиники, больницы)', en: 'Medical Institutions Registry (clinics, hospitals)' },
    description: { ru: 'Геоданные всех медицинских объектов города.', en: 'Geodata of all city medical facilities.' },
    departmentId: 'D7', domainId: 'DOM2', categoryId: 'CAT2.3', type: 'Geodata', format: 'GeoJSON', qualityScore: 93, lastUpdated: '2025-01-10', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['health', 'hospitals'], popularity: 87
  },
  {
    id: '17',
    name: { ru: 'Зоны обслуживания поликлиник (полигоны)', en: 'Clinic Service Zones (polygons)' },
    description: { ru: 'Территориальное распределение зон обслуживания поликлиник.', en: 'Territorial distribution of clinic service zones.' },
    departmentId: 'D7', domainId: 'DOM2', categoryId: 'CAT2.3', type: 'Geodata', format: 'SHP', qualityScore: 80, lastUpdated: '2024-06-01', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['health', 'zones'], popularity: 68
  },
  {
    id: '18',
    name: { ru: 'Статистика вызовов скорой помощи (агрегированная)', en: 'Ambulance Call Statistics (aggregated)' },
    description: { ru: 'Агрегированные данные по вызовам скорой помощи.', en: 'Aggregated data on ambulance calls.' },
    departmentId: 'D7', domainId: 'DOM2', categoryId: 'CAT2.3', type: 'Table', format: 'CSV', qualityScore: 76, lastUpdated: '2025-02-15', frequency: 'Monthly', access: 'Restricted', status: 'active', isPrivate: false, tags: ['ambulance', 'stats'], popularity: 58
  },
  {
    id: '19',
    name: { ru: 'Реестр социальных учреждений', en: 'Social Institutions Registry' },
    description: { ru: 'Список объектов социальной защиты населения.', en: 'List of social protection facilities.' },
    departmentId: 'D8', domainId: 'DOM2', categoryId: 'CAT2.4', type: 'Geodata', format: 'GeoJSON', qualityScore: 85, lastUpdated: '2024-11-01', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['social', 'services'], popularity: 72
  },
  {
    id: '20',
    name: { ru: 'Статистика получателей адресной социальной помощи', en: 'Targeted Social Assistance Recipients Statistics' },
    description: { ru: 'Данные о получателях АСП.', en: 'Data on TSA recipients.' },
    departmentId: 'D8', domainId: 'DOM2', categoryId: 'CAT2.4', type: 'Table', format: 'Excel', qualityScore: 82, lastUpdated: '2025-01-30', frequency: 'Quarterly', access: 'Restricted', status: 'active', isPrivate: false, tags: ['social', 'stats'], popularity: 52
  },

  // DOMAIN 3
  {
    id: '21',
    name: { ru: 'Граф улично-дорожной сети (линии, классы дорог)', en: 'Road Network Graph (lines, road classes)' },
    description: { ru: 'Полный граф дорог города с атрибутами.', en: 'Complete city road graph with attributes.' },
    departmentId: 'D4', domainId: 'DOM3', categoryId: 'CAT3.1', type: 'Geodata', format: 'SHP', qualityScore: 89, lastUpdated: '2025-01-20', frequency: 'Quarterly', access: 'Open', status: 'active', isPrivate: false, tags: ['roads', 'transport'], popularity: 93
  },
  {
    id: '22',
    name: { ru: 'Реестр состояния дорожного покрытия', en: 'Road Surface Condition Registry' },
    description: { ru: 'Данные о качестве дорожного полотна.', en: 'Data on road surface quality.' },
    departmentId: 'D4', domainId: 'DOM3', categoryId: 'CAT3.1', type: 'Table', format: 'Excel', qualityScore: 74, lastUpdated: '2024-10-15', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['roads', 'quality'], popularity: 64
  },
  {
    id: '23',
    name: { ru: 'Статистика ДТП (геоточки, 2020-2025)', en: 'Accident Statistics (geopoints, 2020-2025)' },
    description: { ru: 'Данные о дорожно-транспортных происшествиях.', en: 'Data on road traffic accidents.' },
    departmentId: 'D4', domainId: 'DOM3', categoryId: 'CAT3.1', type: 'Geodata', format: 'GeoJSON', qualityScore: 85, lastUpdated: '2025-02-10', frequency: 'Monthly', access: 'By Request', status: 'active', isPrivate: false, tags: ['accidents', 'safety'], popularity: 79
  },
  {
    id: '24',
    name: { ru: 'Маршрутная сеть автобусов и БРТ (GTFS)', en: 'Bus and BRT Route Network (GTFS)' },
    description: { ru: 'Данные о маршрутах общественного транспорта в формате GTFS.', en: 'Public transport route data in GTFS format.' },
    departmentId: 'D5', domainId: 'DOM3', categoryId: 'CAT3.2', type: 'Geodata', format: 'GTFS', qualityScore: 92, lastUpdated: '2025-03-01', frequency: 'Monthly', access: 'Open', status: 'active', isPrivate: false, tags: ['bus', 'gtfs'], popularity: 96
  },
  {
    id: '25',
    name: { ru: 'Маршруты Astana LRT', en: 'Astana LRT Routes' },
    description: { ru: 'Схема линий легкорельсового транспорта.', en: 'Light rail transport line scheme.' },
    departmentId: 'D5', domainId: 'DOM3', categoryId: 'CAT3.2', type: 'Geodata', format: 'GeoJSON', qualityScore: 95, lastUpdated: '2025-01-15', frequency: 'Quarterly', access: 'Open', status: 'active', isPrivate: false, tags: ['lrt', 'transport'], popularity: 81
  },
  {
    id: '26',
    name: { ru: 'Данные валидации проездных (агрегированные, по остановкам)', en: 'Ticket Validation Data (aggregated, by stops)' },
    description: { ru: 'Статистика пассажиропотока на основе валидаций.', en: 'Passenger flow statistics based on validations.' },
    departmentId: 'D5', domainId: 'DOM3', categoryId: 'CAT3.2', type: 'Table', format: 'CSV', qualityScore: 88, lastUpdated: '2025-02-28', frequency: 'Monthly', access: 'By Request', status: 'active', isPrivate: false, tags: ['passengers', 'stats'], popularity: 74
  },
  {
    id: '27',
    name: { ru: 'Реестр парковочных мест (координаты, вместимость)', en: 'Parking Spaces Registry (coordinates, capacity)' },
    description: { ru: 'Данные о парковках города.', en: 'Data on city parking lots.' },
    departmentId: 'D4', domainId: 'DOM3', categoryId: 'CAT3.3', type: 'Geodata', format: 'GeoJSON', qualityScore: 71, lastUpdated: '2024-08-01', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['parking', 'transport'], popularity: 61
  },
  {
    id: '28',
    name: { ru: 'Схема велосипедных дорожек', en: 'Bicycle Paths Scheme' },
    description: { ru: 'Геоданные велоинфраструктуры города.', en: 'Geodata of city bicycle infrastructure.' },
    departmentId: 'D4', domainId: 'DOM3', categoryId: 'CAT3.3', type: 'Geodata', format: 'SHP', qualityScore: 77, lastUpdated: '2024-07-15', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['bike', 'cycling'], popularity: 67
  },

  // DOMAIN 4
  {
    id: '29',
    name: { ru: 'Мониторинг PM2.5 / PM10 (станции, ежечасно)', en: 'PM2.5 / PM10 Monitoring (stations, hourly)' },
    description: { ru: 'Данные о качестве воздуха в реальном времени.', en: 'Real-time air quality data.' },
    departmentId: 'D13', domainId: 'DOM4', categoryId: 'CAT4.1', type: 'Stream', format: 'API', qualityScore: 90, lastUpdated: '2026-03-07', frequency: 'Realtime', access: 'Open', status: 'active', isPrivate: false, tags: ['air', 'ecology'], popularity: 94
  },
  {
    id: '30',
    name: { ru: 'Результаты моделирования рассеивания загрязнений', en: 'Pollution Dispersion Modeling Results' },
    description: { ru: 'Карты распространения загрязнений в атмосфере.', en: 'Maps of pollution dispersion in the atmosphere.' },
    departmentId: 'D13', domainId: 'DOM4', categoryId: 'CAT4.1', type: 'Raster', format: 'GeoTIFF', qualityScore: 83, lastUpdated: '2024-12-01', frequency: 'Annually', access: 'By Request', status: 'active', isPrivate: false, tags: ['pollution', 'modeling'], popularity: 59
  },
  {
    id: '31',
    name: { ru: 'Реестр зелёных насаждений (полигоны, тип, площадь)', en: 'Green Spaces Registry (polygons, type, area)' },
    description: { ru: 'Данные об озеленении города.', en: 'Data on city greening.' },
    departmentId: 'D13', domainId: 'DOM4', categoryId: 'CAT4.2', type: 'Geodata', format: 'SHP', qualityScore: 78, lastUpdated: '2024-09-01', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['green', 'ecology'], popularity: 73
  },
  {
    id: '32',
    name: { ru: 'Границы ООПТ и парковых зон', en: 'Protected Areas and Park Zone Boundaries' },
    description: { ru: 'Границы особо охраняемых природных территорий.', en: 'Boundaries of specially protected natural areas.' },
    departmentId: 'D13', domainId: 'DOM4', categoryId: 'CAT4.2', type: 'Geodata', format: 'GeoJSON', qualityScore: 92, lastUpdated: '2024-06-15', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['parks', 'nature'], popularity: 69
  },
  {
    id: '33',
    name: { ru: 'Гидрологические данные реки Есиль', en: 'Esil River Hydrological Data' },
    description: { ru: 'Показатели состояния реки Есиль.', en: 'Indicators of the state of the Esil River.' },
    departmentId: 'D13', domainId: 'DOM4', categoryId: 'CAT4.3', type: 'Table', format: 'CSV', qualityScore: 81, lastUpdated: '2025-01-01', frequency: 'Quarterly', access: 'By Request', status: 'active', isPrivate: false, tags: ['river', 'water'], popularity: 54
  },
  {
    id: '34',
    name: { ru: 'Метеорологические данные (температура, осадки)', en: 'Meteorological Data (temperature, precipitation)' },
    description: { ru: 'Данные о погоде в реальном времени.', en: 'Real-time weather data.' },
    departmentId: 'D13', domainId: 'DOM4', categoryId: 'CAT4.3', type: 'Stream', format: 'API', qualityScore: 94, lastUpdated: '2026-03-07', frequency: 'Realtime', access: 'Open', status: 'active', isPrivate: false, tags: ['weather', 'stats'], popularity: 88
  },

  // DOMAIN 5
  {
    id: '35',
    name: { ru: 'Схема теплоснабжения (линии, ЦТП, котельные)', en: 'Heat Supply Scheme (lines, heating stations, boiler houses)' },
    description: { ru: 'Инженерные сети теплоснабжения города.', en: 'City heat supply engineering networks.' },
    departmentId: 'D9', domainId: 'DOM5', categoryId: 'CAT5.1', type: 'Geodata', format: 'SHP', qualityScore: 75, lastUpdated: '2024-05-01', frequency: 'Annually', access: 'Restricted', status: 'active', isPrivate: false, tags: ['heating', 'utilities'], popularity: 48
  },
  {
    id: '36',
    name: { ru: 'Сеть водоснабжения и канализации', en: 'Water Supply and Sewerage Network' },
    description: { ru: 'Схема сетей водоканала.', en: 'Water utility network scheme.' },
    departmentId: 'D9', domainId: 'DOM5', categoryId: 'CAT5.1', type: 'Geodata', format: 'SHP', qualityScore: 70, lastUpdated: '2024-04-01', frequency: 'Annually', access: 'Restricted', status: 'active', isPrivate: false, tags: ['water', 'utilities'], popularity: 45
  },
  {
    id: '37',
    name: { ru: 'Электрические сети (подстанции, ЛЭП)', en: 'Electrical Networks (substations, power lines)' },
    description: { ru: 'Схема электросетевого хозяйства.', en: 'Power grid management scheme.' },
    departmentId: 'D9', domainId: 'DOM5', categoryId: 'CAT5.1', type: 'Geodata', format: 'SHP', qualityScore: 73, lastUpdated: '2024-06-01', frequency: 'Annually', access: 'Restricted', status: 'active', isPrivate: false, tags: ['electricity', 'utilities'], popularity: 42
  },
  {
    id: '38',
    name: { ru: 'Реестр объектов благоустройства (площадки, скверы)', en: 'Public Amenities Registry (playgrounds, squares)' },
    description: { ru: 'Список объектов городского благоустройства.', en: 'List of city improvement objects.' },
    departmentId: 'D9', domainId: 'DOM5', categoryId: 'CAT5.2', type: 'Geodata', format: 'GeoJSON', qualityScore: 80, lastUpdated: '2025-01-15', frequency: 'Quarterly', access: 'Open', status: 'active', isPrivate: false, tags: ['amenities', 'improvement'], popularity: 71
  },
  {
    id: '39',
    name: { ru: 'Данные обращений по санитарному состоянию (iKomek)', en: 'Sanitary Condition Requests Data (iKomek)' },
    description: { ru: 'Статистика обращений граждан по вопросам чистоты.', en: 'Statistics of citizen requests on cleanliness issues.' },
    departmentId: 'D14', domainId: 'DOM5', categoryId: 'CAT5.2', type: 'Table', format: 'CSV', qualityScore: 84, lastUpdated: '2025-03-01', frequency: 'Monthly', access: 'By Request', status: 'active', isPrivate: false, tags: ['ikomek', 'requests'], popularity: 77
  },

  // DOMAIN 6
  {
    id: '40',
    name: { ru: 'Исполнение бюджета по программам (ежеквартально)', en: 'Budget Execution by Programs (quarterly)' },
    description: { ru: 'Отчеты об исполнении городского бюджета.', en: 'Reports on city budget execution.' },
    departmentId: 'D11', domainId: 'DOM6', categoryId: 'CAT6.1', type: 'Table', format: 'Excel', qualityScore: 97, lastUpdated: '2025-01-31', frequency: 'Quarterly', access: 'Open', status: 'active', isPrivate: false, tags: ['budget', 'finance'], popularity: 92
  },
  {
    id: '41',
    name: { ru: 'Инвестиционные расходы по районам', en: 'Investment Expenses by Districts' },
    description: { ru: 'Распределение инвестиций по территории города.', en: 'Distribution of investments across the city territory.' },
    departmentId: 'D11', domainId: 'DOM6', categoryId: 'CAT6.1', type: 'Table', format: 'Excel', qualityScore: 93, lastUpdated: '2024-12-31', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['investments', 'finance'], popularity: 81
  },
  {
    id: '42',
    name: { ru: 'Реестр субъектов МСБ по видам деятельности', en: 'SME Registry by Activity Types' },
    description: { ru: 'Список малого и среднего бизнеса города.', en: 'List of small and medium businesses in the city.' },
    departmentId: 'D12', domainId: 'DOM6', categoryId: 'CAT6.2', type: 'Table', format: 'CSV', qualityScore: 86, lastUpdated: '2025-02-01', frequency: 'Quarterly', access: 'Open', status: 'active', isPrivate: false, tags: ['sme', 'business'], popularity: 86
  },
  {
    id: '43',
    name: { ru: 'Реестр торговых объектов и рынков (координаты)', en: 'Trade Objects and Markets Registry (coordinates)' },
    description: { ru: 'Геоданные торговой инфраструктуры.', en: 'Geodata of trade infrastructure.' },
    departmentId: 'D12', domainId: 'DOM6', categoryId: 'CAT6.2', type: 'Geodata', format: 'GeoJSON', qualityScore: 79, lastUpdated: '2024-11-15', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['trade', 'markets'], popularity: 75
  },

  // DOMAIN 7
  {
    id: '44',
    name: { ru: 'Карта сейсмических зон и микрорайонирования', en: 'Seismic Zones and Microzoning Map' },
    description: { ru: 'Данные о сейсмической опасности территории.', en: 'Data on seismic hazard of the territory.' },
    departmentId: 'D1', domainId: 'DOM7', categoryId: 'CAT7.1', type: 'Raster', format: 'GeoTIFF', qualityScore: 90, lastUpdated: '2023-06-01', frequency: 'Once', access: 'Open', status: 'active', isPrivate: false, tags: ['seismic', 'safety'], popularity: 68
  },
  {
    id: '45',
    name: { ru: 'Карта зон затопления и паводковых рисков', en: 'Flood Zones and Flood Risks Map' },
    description: { ru: 'Территории, подверженные риску затопления.', en: 'Territories at risk of flooding.' },
    departmentId: 'D13', domainId: 'DOM7', categoryId: 'CAT7.1', type: 'Geodata', format: 'SHP', qualityScore: 84, lastUpdated: '2024-03-01', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['flood', 'safety'], popularity: 76
  },
  {
    id: '46',
    name: { ru: 'Расположение пожарных депо и зоны покрытия', en: 'Fire Stations Locations and Coverage Zones' },
    description: { ru: 'Геоданные объектов пожарной службы.', en: 'Geodata of fire service facilities.' },
    departmentId: 'D7', domainId: 'DOM7', categoryId: 'CAT7.1', type: 'Geodata', format: 'GeoJSON', qualityScore: 88, lastUpdated: '2024-09-01', frequency: 'Annually', access: 'Open', status: 'active', isPrivate: false, tags: ['fire', 'safety'], popularity: 64
  },
  {
    id: '47',
    name: { ru: 'Статистика правонарушений по районам (агрегированная)', en: 'Crime Statistics by Districts (aggregated)' },
    description: { ru: 'Данные об уровне преступности.', en: 'Data on crime levels.' },
    departmentId: 'D14', domainId: 'DOM7', categoryId: 'CAT7.2', type: 'Table', format: 'CSV', qualityScore: 77, lastUpdated: '2025-01-15', frequency: 'Quarterly', access: 'Restricted', status: 'active', isPrivate: false, tags: ['crime', 'safety'], popularity: 57
  },
  {
    id: '48',
    name: { ru: 'Расположение камер видеонаблюдения «Сергек»', en: 'Sergek Video Surveillance Cameras Locations' },
    description: { ru: 'Геоданные системы видеонаблюдения.', en: 'Geodata of the video surveillance system.' },
    departmentId: 'D14', domainId: 'DOM7', categoryId: 'CAT7.2', type: 'Geodata', format: 'GeoJSON', qualityScore: 91, lastUpdated: '2025-02-01', frequency: 'Monthly', access: 'Restricted', status: 'active', isPrivate: false, tags: ['sergek', 'safety'], popularity: 82
  },
];

export const GOVERNANCE_TASKS: GovernanceTask[] = [
  {
    id: 't1',
    title: { en: 'Fix missing values in Building Permits', ru: 'Исправить пропущенные значения в Разрешениях на строительство' },
    datasetId: '8',
    status: 'in-progress',
    priority: 'high',
    assignee: 'Sanzhar K.',
    dueDate: '2024-03-10',
  },
];

export const TRANSLATIONS = {
  en: {
    searchPlaceholder: "Ask AI about city data...",
    catalogSearchPlaceholder: "Search by keywords",
    home: "Home",
    catalog: "Data Library",
    geoAnalytics: "GeoAnalytics",
    documents: "Documentation Canvas",
    sidebarDocuments: "Documentation Canvas",
    documentsTitle: "Documentation Canvas",
    populationDensity: "Population density 2023",
    transportReports: "Transport reports",
    aqiSensors: "AQI sensors Astana",
    buildingPermits: "Building permits",
    analyticalBrief: "Analytical Brief",
    districtReport: "District Report",
    riskAssessment: "Risk Assessment",
    budgetJustification: "Budget Justification",
    newDocument: "New Document",
    startWithTemplate: "Start with a Template",
    aiTemplateNote: "AI-powered template with auto-population.",
    recentDocuments: "Recent Documents",
    searchDocuments: "Search documents...",
    save: "Save",
    share: "Share",
    export: "Export",
    insertBlocks: "Insert Blocks",
    text: "Text",
    image: "Image",
    table: "Table",
    map: "Map",
    chart: "Chart",
    aiBlock: "AI Block",
    aiAssistant: "AI Assistant",
    writingAssistant: "Writing Assistant",
    aiWritingNote: "I can help you draft conclusions based on the population density data you analyzed in GeoAnalytics.",
    generateNarrative: "Generate Narrative",
    authorName: "Author: Alisher Yerzhanov",
    dateLabel: "Date: March 1, 2024",
    dragBlocksNote: "Drag blocks here to build your report",
    draft: "Draft",
    governance: "Data Governance",
    workspace: "Workspace",
    cityLibrary: "City Library",
    myDepartment: "My Department",
    myFiles: "My Files",
    recentActivity: "Recent Activity",
    pinned: "Pinned",
    quality: "Quality",
    status: "Status",
    format: "Format",
    updated: "Updated",
    aiCopilot: "AI Copilot",
    governanceDashboard: "Governance Dashboard",
    taskBoard: "Task Board",
    search: "Search",
    filters: "Filters",
    allDepartments: "All Departments",
    allCategories: "All Categories",
    allFormats: "All Formats",
    apply: "Apply",
    reset: "Reset",
    passport: "Data Object Passport",
    overview: "Overview",
    metadata: "Metadata",
    lineage: "Lineage",
    preview: "Preview",
    access: "Access",
    activity: "Activity",
    description: "Description",
    owner: "Owner",
    responsible: "Responsible",
    completeness: "Completeness",
    accuracy: "Accuracy",
    timeliness: "Timeliness",
    consistency: "Consistency",
    inProgress: "In Progress",
    review: "Review",
    done: "Done",
    high: "High",
    medium: "Medium",
    low: "Low",
    projects: "Projects",
    team: "Team",
    sharedWithUs: "Shared with us",
    language: "Language",
    theme: "Theme",
    logout: "Logout",
    settings: "Settings",
    help: "Help",
    found: "Found",
    dataObjects: "data objects",
    sortBy: "Sort by",
    updateDate: "Update date",
    name: "Name",
    popularity: "Popularity",
    tree: "Tree",
    grid: "Grid",
    list: "List",
    noResults: "No data objects found for selected filters",
    tryReset: "Try changing search parameters",
    domains: "Domains",
    dataType: "Data Type",
    frequency: "Frequency",
    accessLevel: "Access Level",
    qualityStatus: "Quality Status",
    period: "Period",
    realtime: "Realtime",
    daily: "Daily",
    weekly: "Weekly",
    monthly: "Monthly",
    quarterly: "Quarterly",
    annually: "Annually",
    once: "Once",
    asNeeded: "As needed",
    open: "Open",
    byRequest: "By Request",
    restricted: "Restricted",
    highQuality: "High (>85%)",
    lowQuality: "Low (<60%)",
    mediumQuality: "Medium (60-85%)",
    backToCatalog: "Back to Catalog",
    requestAccess: "Request Access",
    download: "Download",
    favorite: "Favorite",
    coverageArea: "Coverage Area",
    keyAttributes: "Key Attributes",
    field: "Field",
    type: "Type",
    dataSchema: "Data Schema",
    technicalDetails: "Technical Details",
    classifications: "Classifications",
    overallQuality: "Overall Quality Index",
    validationDetails: "Validation Details",
    check: "Check",
    result: "Result",
    date: "Date",
    details: "Details",
    relatedTasks: "Related Quality Tasks",
    upstreamSources: "Upstream Sources",
    downstreamConsumers: "Downstream Consumers",
    historyTransformations: "History of Transformations",
    statisticsSummary: "Statistics Summary",
    totalRecords: "Total Records",
    minDensity: "Min Density",
    maxDensity: "Max Density",
    avgDensity: "Avg Density",
    totalPopulation: "Total Population",
    whoHasAccess: "Who Has Access",
    recentRequests: "Recent Access Requests",
    activityFeed: "Activity Feed",
    versionHistory: "Version History",
    version: "Version",
    author: "Author",
    changes: "Changes",
    purpose: "Purpose of Use",
    periodAccess: "Desired Access Period",
    sendRequest: "Send Request",
    user: "User",
    role: "Role",
    accessFrom: "Access From",
    expires: "Expires",
    applicant: "Applicant",
    requestDate: "Request Date",
    event: "Event",
    timestamp: "Timestamp",
    allEvents: "All Events",
    dataUpdates: "Data Updates",
    qualityEvents: "Quality",
    accessEvents: "Access",
    metadataEvents: "Metadata",
    lastMonth: "Last Month",
    lastQuarter: "Last Quarter",
    lastYear: "Last Year",
    allTime: "All Time",
    passed: "Passed",
    warning: "Warning",
    failed: "Failed",
    steward: "Steward",
    volume: "Volume",
    crs: "CRS",
    source: "Source",
    publishedDate: "Published Date",
    license: "License",
    tags: "Tags",
    relatedDatasets: "Related Datasets",
    activityLog: "Activity Log",
    stewardRole: "Steward",
    ownerRole: "Author",
    analystRole: "Analyst",
    adminRole: "Admin",
    myObjects: "My Objects",
    publishNew: "Publish New Data Object",
    edit: "Edit",
    manageAccess: "Manage Access",
    authorRole: "Author",
    userReviews: "User Reviews",
    writeReview: "Write a Review",
    verified: "Verified",
    machineScore: "Machine Score",
    expertScore: "Expert Score",
    expertAssessment: "Author's Quality Assessment",
    communityRating: "Community Rating",
    rateDataset: "Rate this dataset",
    authorComment: "Author's Comment",
    stewardReview: "Steward Review",
    confirmed: "Confirmed",
    needsClarification: "Needs Clarification",
    challenged: "Challenged",
    passportCompleteness: "Passport Completeness",
    missingFields: "Missing Fields",
    machineAssessment: "Machine Assessment",
    expertCommunityAssessment: "Expert & Community Assessment",
    conformity: "Conformity",
    overallMachineIndex: "Overall Machine Quality Index",
    weightedScore: "Weighted Score",
    worstField: "Worst Field",
    daysUntilUpdate: "Days until next expected update",
    businessRules: "Business Rules",
    viewAllReviews: "View all reviews",
    combinedQuality: "Combined Quality Card",
    measurement: "Measurement",
    method: "Method",
    combinedIndex: "Overall Index",
    userRatingNote: "User rating is displayed separately and is not included in the overall quality index calculation.",
    dqDashboard: "DQ Dashboard",
    dqTaskBoard: "DQ Task Board",
    dqMethodology: "DQ Methodology",
    interDepartmental: "Inter-departmental",
    myDepartmentView: "My Department",
    totalDataObjects: "Total Data Objects",
    avgQualityIndex: "Avg Quality Index",
    objectsNeedAttention: "Objects Need Attention",
    activeQualityTasks: "Active Quality Tasks",
    qualityByDept: "Data Quality Status by Department",
    qualityByDomain: "Data Quality by Domain",
    qualityDimensionsBreakdown: "Quality Dimensions Breakdown",
    timelinessAlerts: "Timeliness Alerts",
    overdue: "Overdue",
    expected: "Expected",
    myDeptObjects: "My Department's Data Objects",
    expertAssessmentStatus: "Expert Assessment Status",
    lastAssessment: "Last Assessment",
    upToDate: "Up to Date",
    needsReview: "Needs Review",
    oldAssessment: "Assessment > 1 year",
    backlog: "Backlog",
    inWork: "In Work",
    onReview: "On Review",
    completed: "Completed",
    priority: "Priority",
    assignee: "Assignee",
    manual: "Manual",
    auto: "Auto",
    methodologyOverview: "Methodology Overview",
    qualityFramework: "Quality Framework",
    qualityDimensions: "Quality Dimensions",
    overallQualityIndex: "Overall Quality Index",
    rolesResponsibilities: "Roles & Responsibilities",
    procedures: "Procedures",
    highPriority: "High Priority",
    overdueTasks: "Overdue Tasks",
    completedThisMonth: "Completed this month",
    takeInWork: "Take in Work",
    approve: "Approve",
    return: "Return",
    pending: "Pending",
    approved: "Approved",
    rejected: "Rejected",
    stewardReviewTab: "Steward Review",
    expertAssessments: "Expert Assessments",
    reviewAction: "Review",
    assessmentDetails: "Assessment Details",
    accuracyScore: "Accuracy",
    relevanceScore: "Relevance",
    expertComment: "Expert Comment",
    reject: "Reject",
    clarify: "Clarify",
    findCityData: "Find any city data with AI",
    citipediaConnects: "Citipedia connects all municipal departments into a single searchable knowledge base.",
    suggestions: "Suggestions",
    exploreCatalog: "Explore Catalog",
    analyzeSpatial: "Analyze spatial patterns and run AI-assisted urban simulations.",
    openMap: "Open Map",
    generateAnalytical: "Generate analytical reports and policy briefs with AI writing assistant.",
    createReport: "Create Report",
    viewAll: "View All",
    manage: "Manage",
    platformUpdate: "Platform Update",
    newDatasetsAdded: "5 new datasets added by Transport Department this week. Check the catalog for details.",
    members: "Members",
    files: "Files",
    activeProjects: "Active Projects",
    newProject: "New Project",
    searchFiles: "Search files...",
    uploaded: "uploaded",
    edited: "edited",
    shared: "shared",
    lastUpdated: "Last updated",
    aiMistakes: "AI can make mistakes. Verify critical data.",
    compositeIndex: "Composite Index",
    resilience: "Resilience",
    dataFlowDiagram: "Data Flow Diagram",
    external: "External",
    internal: "Internal",
    system: "System",
    currentAsset: "Current Asset",
    cleaningValidation: "Cleaning & Validation",
    duplicateRemoval: "Duplicate removal, geometry check",
    dataEnrichment: "Data Enrichment",
    linkingKato: "Linking to 2023 KATO codes",
    importAddressRegister: "Import from Address Register",
    initialDataLoad: "Initial data load",
  },
  ru: {
    searchPlaceholder: "Спросите ИИ о городских данных...",
    catalogSearchPlaceholder: "Поиск по ключевым словам",
    home: "Главная",
    catalog: "Библиотека данных",
    geoAnalytics: "ГеоАналитика",
    documents: "Конструктор документов",
    sidebarDocuments: "Документы",
    documentsTitle: "Конструктор документов",
    populationDensity: "Плотность населения 2023",
    transportReports: "Транспортные отчеты",
    aqiSensors: "Датчики качества воздуха Астана",
    buildingPermits: "Разрешения на строительство",
    analyticalBrief: "Аналитическая записка",
    districtReport: "Отчет по району",
    riskAssessment: "Оценка рисков",
    budgetJustification: "Обоснование бюджета",
    newDocument: "Новый документ",
    startWithTemplate: "Начать с шаблона",
    aiTemplateNote: "Шаблон с поддержкой ИИ и автозаполнением.",
    recentDocuments: "Недавние документы",
    searchDocuments: "Поиск документов...",
    save: "Сохранить",
    share: "Поделиться",
    export: "Экспорт",
    insertBlocks: "Вставить блоки",
    text: "Текст",
    image: "Изображение",
    table: "Таблица",
    map: "Карта",
    chart: "График",
    aiBlock: "ИИ Блок",
    aiAssistant: "ИИ Помощник",
    writingAssistant: "Помощник по письму",
    aiWritingNote: "Я могу помочь вам составить выводы на основе данных о плотности населения, которые вы проанализировали в ГеоАналитике.",
    generateNarrative: "Сгенерировать текст",
    authorName: "Автор: Алишер Ержанов",
    dateLabel: "Дата: 1 марта 2024",
    dragBlocksNote: "Перетащите блоки сюда, чтобы построить отчет",
    draft: "Черновик",
    governance: "Управление качеством",
    workspace: "Рабочая область",
    cityLibrary: "Городская библиотека",
    myDepartment: "Моё управление",
    myFiles: "Мои файлы",
    recentActivity: "Недавняя активность",
    pinned: "Закрепленные",
    quality: "Качество",
    format: "Формат",
    updated: "Обновлено",
    aiCopilot: "ИИ Копилот",
    governanceDashboard: "Панель управления",
    taskBoard: "Доска задач",
    search: "Поиск",
    filters: "Фильтры",
    allDepartments: "Все управления",
    allCategories: "Все категории",
    allFormats: "Все форматы",
    apply: "Применить",
    reset: "Сбросить",
    passport: "Паспорт объекта данных",
    overview: "Обзор",
    metadata: "Метаданные",
    lineage: "Происхождение",
    preview: "Предпросмотр",
    access: "Доступ",
    activity: "Активность",
    description: "Описание",
    owner: "Владелец",
    responsible: "Ответственный",
    completeness: "Полнота",
    accuracy: "Точность",
    timeliness: "Своевременность",
    consistency: "Согласованность",
    inProgress: "В процессе",
    review: "Проверка",
    done: "Готово",
    high: "Высокий",
    medium: "Средний",
    low: "Низкий",
    projects: "Проекты",
    team: "Команда",
    sharedWithUs: "Поделились с нами",
    language: "Язык",
    theme: "Тема",
    logout: "Выйти",
    settings: "Настройки",
    help: "Помощь",
    found: "Найдено",
    dataObjects: "объектов данных",
    sortBy: "Сортировать по",
    updateDate: "Дате обновления",
    name: "Названию",
    popularity: "Популярности",
    tree: "Дерево",
    grid: "Сетка",
    list: "Список",
    noResults: "Нет объектов данных по выбранным фильтрам",
    tryReset: "Попробуйте изменить параметры поиска",
    domains: "Домены",
    dataType: "Тип данных",
    frequency: "Частота",
    accessLevel: "Уровень доступа",
    qualityStatus: "Статус качества",
    period: "Период",
    realtime: "Реалтайм",
    daily: "Ежедневно",
    weekly: "Еженедельно",
    monthly: "Ежемесячно",
    quarterly: "Ежеквартально",
    annually: "Ежегодно",
    once: "Разово",
    asNeeded: "По мере разработки",
    open: "Открытый",
    byRequest: "По запросу",
    restricted: "Ограниченный",
    highQuality: "Высокое (>85%)",
    lowQuality: "Низкое (<60%)",
    mediumQuality: "Среднее (60-85%)",
    backToCatalog: "Назад в каталог",
    requestAccess: "Запросить доступ",
    download: "Скачать",
    favorite: "В избранное",
    coverageArea: "Территория покрытия",
    keyAttributes: "Ключевые параметры",
    field: "Поле",
    type: "Тип",
    dataSchema: "Схема данных",
    technicalDetails: "Технические параметры",
    classifications: "Классификаторы",
    overallQuality: "Общий индекс качества",
    validationDetails: "Детализация проверок",
    check: "Проверка",
    result: "Результат",
    date: "Дата",
    details: "Детали",
    relatedTasks: "Связанные задачи по качеству",
    upstreamSources: "Источники",
    downstreamConsumers: "Потребители",
    historyTransformations: "История обработки",
    statisticsSummary: "Статистическая сводка",
    totalRecords: "Всего записей",
    minDensity: "Мин. плотность",
    maxDensity: "Макс. плотность",
    avgDensity: "Средняя плотность",
    totalPopulation: "Общее население",
    whoHasAccess: "Кто имеет доступ",
    recentRequests: "Последние запросы доступа",
    activityFeed: "Лента активности",
    versionHistory: "История версий",
    version: "Версия",
    author: "Автор",
    changes: "Изменения",
    purpose: "Цель использования",
    periodAccess: "Желаемый период доступа",
    sendRequest: "Отправить запрос",
    user: "Пользователь",
    role: "Роль",
    accessFrom: "Доступ с",
    expires: "Истекает",
    applicant: "Заявитель",
    requestDate: "Дата запроса",
    status: "Статус",
    event: "Событие",
    timestamp: "Время",
    allEvents: "Все события",
    dataUpdates: "Обновления данных",
    qualityEvents: "Качество",
    accessEvents: "Доступ",
    metadataEvents: "Метаданные",
    lastMonth: "За месяц",
    lastQuarter: "За квартал",
    lastYear: "За год",
    allTime: "Все время",
    passed: "Пройдена",
    warning: "Предупреждение",
    failed: "Ошибка",
    steward: "Ответственный",
    volume: "Объём",
    crs: "Система координат",
    source: "Источник",
    publishedDate: "Дата публикации",
    license: "Лицензия",
    tags: "Теги",
    relatedDatasets: "Связанные данные",
    activityLog: "Журнал активности",
    stewardRole: "Стюард",
    ownerRole: "Автор",
    analystRole: "Аналитик",
    adminRole: "Админ",
    myObjects: "Мои объекты",
    publishNew: "Опубликовать новый объект данных",
    edit: "Редактировать",
    manageAccess: "Управление доступом",
    authorRole: "Автор",
    userReviews: "Отзывы пользователей",
    writeReview: "Написать отзыв",
    verified: "Проверено",
    machineScore: "Машинная оценка",
    expertScore: "Экспертная оценка",
    expertAssessment: "Экспертная оценка автора",
    communityRating: "Пользовательский рейтинг",
    rateDataset: "Оценить этот датасет",
    authorComment: "Комментарий автора",
    stewardReview: "Ревью стюарда",
    confirmed: "Подтверждено",
    needsClarification: "Требует уточнения",
    challenged: "Оспорено",
    passportCompleteness: "Полнота паспорта",
    missingFields: "Не заполнены",
    machineAssessment: "Автоматическая оценка",
    expertCommunityAssessment: "Экспертная и пользовательская оценка",
    conformity: "Формальная корректность",
    overallMachineIndex: "Общий индекс машинного качества",
    weightedScore: "Взвешенная оценка",
    worstField: "Худшее поле",
    daysUntilUpdate: "Дней до следующего обновления",
    businessRules: "Бизнес-правила",
    viewAllReviews: "Смотреть все отзывы",
    combinedQuality: "Комбинированная карточка качества",
    measurement: "Измерение",
    method: "Метод",
    combinedIndex: "Общий индекс",
    userRatingNote: "Пользовательский рейтинг отображается отдельно и не входит в расчёт общего индекса качества.",
    dqDashboard: "Панель DQ",
    dqTaskBoard: "Доска задач DQ",
    dqMethodology: "Методология DQ",
    interDepartmental: "Межведомственный",
    myDepartmentView: "Моё управление",
    totalDataObjects: "Всего объектов данных",
    avgQualityIndex: "Средний индекс качества",
    objectsNeedAttention: "Объектов требуют внимания",
    activeQualityTasks: "Активных задач по качеству",
    qualityByDept: "Статус качества данных по управлениям",
    qualityByDomain: "Качество данных по доменам",
    qualityDimensionsBreakdown: "Разбивка по измерениям качества",
    timelinessAlerts: "Оповещения о своевременности",
    overdue: "Просрочка",
    expected: "Ожидалось",
    myDeptObjects: "Объекты данных моего управления",
    expertAssessmentStatus: "Статус экспертной оценки",
    lastAssessment: "Последняя оценка",
    upToDate: "Актуально",
    needsReview: "Требует ревью",
    oldAssessment: "Оценке > 1 года",
    backlog: "Бэклог",
    inWork: "В работе",
    onReview: "На ревью",
    completed: "Завершено",
    priority: "Приоритет",
    assignee: "Исполнитель",
    manual: "Ручная",
    auto: "Авто",
    methodologyOverview: "Обзор методологии",
    qualityFramework: "Фреймворк качества",
    qualityDimensions: "Измерения качества",
    overallQualityIndex: "Общий индекс качества",
    rolesResponsibilities: "Роли и ответственности",
    procedures: "Процедуры",
    highPriority: "Высокий приоритет",
    overdueTasks: "Просроченные задачи",
    completedThisMonth: "Завершено за этот месяц",
    takeInWork: "Взять в работу",
    approve: "Одобрить",
    return: "Вернуть",
    pending: "Ожидает",
    approved: "Одобрено",
    rejected: "Отклонено",
    stewardReviewTab: "Ревью стюарда",
    expertAssessments: "Экспертные оценки",
    reviewAction: "Проверить",
    assessmentDetails: "Детали оценки",
    accuracyScore: "Точность",
    relevanceScore: "Актуальность",
    expertComment: "Комментарий эксперта",
    reject: "Отклонить",
    clarify: "Уточнить",
    findCityData: "Найдите любые городские данные с помощью ИИ",
    citipediaConnects: "Citipedia объединяет все муниципальные управления в единую базу знаний с поиском.",
    suggestions: "Предложения",
    exploreCatalog: "Перейти в библиотеку",
    analyzeSpatial: "Анализируйте пространственные закономерности и запускайте ИИ-симуляции развития города.",
    openMap: "Открыть карту",
    generateAnalytical: "Создавайте аналитические отчеты и пояснительные записки с помощью ИИ-помощника.",
    createReport: "Создать отчет",
    viewAll: "Смотреть все",
    manage: "Управление",
    platformUpdate: "Обновление платформы",
    newDatasetsAdded: "На этой неделе Управлением транспорта добавлено 5 новых наборов данных. Проверьте библиотеку для деталей.",
    members: "Участники",
    files: "Файлы",
    activeProjects: "Активные проекты",
    newProject: "Новый проект",
    searchFiles: "Поиск файлов...",
    uploaded: "загрузил(а)",
    edited: "изменил(а)",
    shared: "поделился(ась)",
    lastUpdated: "Последнее обновление",
    aiMistakes: "ИИ может ошибаться. Проверяйте критически важные данные.",
    compositeIndex: "Композитный индекс",
    resilience: "Устойчивость",
    dataFlowDiagram: "Диаграмма потоков данных",
    external: "Внешний",
    internal: "Внутренний",
    system: "Системный",
    currentAsset: "Текущий актив",
    cleaningValidation: "Очистка и валидация",
    duplicateRemoval: "Удаление дубликатов, проверка геометрии",
    dataEnrichment: "Обогащение данными",
    linkingKato: "Привязка к кодам КАТО 2023",
    importAddressRegister: "Импорт из Адресного регистра",
    initialDataLoad: "Первичная загрузка данных",
  },
};
